sudo: false
language: ruby
rvm:
- 2.3.1
before_install: gem install bundler -v 1.12.5
notifications:
  slack:
    secure: VPzFgTybKgKLS3VLsVMJuNppYGao6F1ku7lb7XY/RXcVwKTcgQC32suO3dnoqbtUpijRwlLj0rtTD1gdJ4Dceq+g9OEj3bVr07ifDFkOSQfs0/ckh2bCBN8NWVJJzHSKJuzKz7KhGPYYNvdDV8DumqxotL6fPHojoK8lQjmv+qp0ySZnkDr7S0mhzTuRtqb0NQ/uGKnaLtCiS2EGECghNK1eijLuNVc+eJ1IhpalCYS5I0tOTVftj3/e7GbQW8p26XgtcgB9QMhXLJjRGHsLNkBFDrOmSnG0mzvIXFARbklfvd8ZmeuwcxN1hy9dfcLwlCkgII/6CMVd7O4g9tsrRB02WaGoLzbZfcjFJqD3kEhUza7AdNtBAtAv1OSqxc+KHEmWJqMQUd5crLwd4wHZZw82ouWd0HGlZw/Ueqyl1m0Xi7Otj9UeAxz6PQQQAn3Xuxt6mNQhFjKHHVZT63kosPKuzFjZ+f7y/37k8vxTadzf3Fjjcz1NmvG2tR02xs0vj+WskIYpOw9KELwlyiQAf71dSGBaNExGULKVusI0EIXvqTff46ZxoeFwR6gg3Jxh50mqjpux9Azc52pULzkExib0Cx/+O6vDBiPvVT4DKOCA87WmxN2ecXE3uasit5ZEZgGUsFjMmP8NbqIRp60jn8GCstR1f866YkWVPbvcIvs=
